### PR TITLE
locales

### PR DESCRIPTION
**Pull request by ovari**
Does `pt-PT` work? Or does it all need to be in lowercase? What is the convention? Thank you

### CODE REVIEW

**Comment by JohnMcLear** [comment]
@ovari IDK, the convention is whatever comes from @translatewiki as all translations have to come through their platform.

If you can, jump on https://discord.gg/daEjfhw and chat w/ NikeRabbit as he manages our translations :)

**Comment by ovari** [comment]
> @ovari IDK, the convention is whatever comes from @translatewiki as all translations have to come through their platform.

From https://translatewiki.net/, there seems to be many more languages than this pull request has, can you please accept this pull request?

> If you can, jump on https://discord.gg/daEjfhw and chat w/ NikeRabbit as he manages our translations :)

Sorry, we don't have a discord account. We have a [Jami account](https://jami.net/).

Thank you

**Comment by JohnMcLear** [comment]
Will wait to see what @translatewiki  comes back with before merging.  If it goes stale lemme know

**Comment by ovari** [comment]
> Will wait to see what @translatewiki comes back with before merging. If it goes stale lemme know

Can you please advise how long does it takes to go stale? Thank you

**Comment by Nikerabbit** [comment]
You can see our list of codes in https://translatewiki.net/wiki/Special:MessageGroupStats?group=etherpad-lite&x=D

We also support code maps if someone provides a list.

**Comment by ovari** [comment]
> You can see our list of codes in https://translatewiki.net/wiki/Special:MessageGroupStats?group=etherpad-lite&x=D
> 
> We also support code maps if someone provides a list.

Can you please add `hu-hung` for `Székely–magyar rovásírás`
https://hu.wikipedia.org/wiki/Sz%C3%A9kely%E2%80%93magyar_rov%C3%A1s%C3%ADr%C3%A1s
https://bugs.documentfoundation.org/show_bug.cgi?id=97406

Thank you

**Comment by Nikerabbit** [comment]
We have a process for adding new languages: https://translatewiki.net/wiki/Translatewiki.net_languages

You can also add `hu-hung` translation directly to repository if you wish, it will not be touched by translatewiki.net.

**Pull request merged**
